from __future__ import annotations

_CONNECTOR_TIERS = {
    "postgres": {
        "tier": 1,
        "label": "Tier 1 — Full Support",
        "features": {
            "ssl": True,
            "ssh_tunnel": True,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": True,
            "row_counts": True,
            "column_stats": True,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": True,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": True,
            "parallel_schema": True,
            "table_sizes": True,
            "iam_auth": True,
        },
    },
    "mysql": {
        "tier": 1,
        "label": "Tier 1 — Full Support",
        "features": {
            "ssl": True,
            "ssh_tunnel": True,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": True,
            "row_counts": True,
            "column_stats": True,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": False,
            "table_sizes": True,
            "iam_auth": True,
        },
    },
    "snowflake": {
        "tier": 1,
        "label": "Tier 1 — Full Support",
        "features": {
            "ssl": False,
            "ssh_tunnel": False,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": False,
            "row_counts": True,
            "column_stats": False,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": True,
            "key_pair_auth": True,
            "oauth_auth": True,
            "warehouse_config": True,
            "table_sizes": True,
        },
    },
    "bigquery": {
        "tier": 1,
        "label": "Tier 1 — Full Support",
        "features": {
            "ssl": False,
            "ssh_tunnel": False,
            "schema_introspection": True,
            "foreign_keys": False,
            "indexes": False,
            "row_counts": True,
            "column_stats": False,
            "primary_keys": False,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": False,
            "partitioning_info": True,
            "clustering_info": True,
            "service_account_auth": True,
        },
    },
    "redshift": {
        "tier": 2,
        "label": "Tier 2 — Stable",
        "features": {
            "ssl": True,
            "ssh_tunnel": True,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": False,
            "row_counts": True,
            "column_stats": True,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": True,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": True,
            "dist_sort_keys": True,
            "iam_auth": True,
            "table_sizes": True,
        },
    },
    "clickhouse": {
        "tier": 2,
        "label": "Tier 2 — Stable",
        "features": {
            "ssl": True,
            "ssh_tunnel": True,
            "schema_introspection": True,
            "foreign_keys": False,
            "indexes": False,
            "row_counts": True,
            "column_stats": True,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": False,
            "engine_info": True,
            "sorting_key_info": True,
            "native_and_http": True,
            "table_sizes": True,
        },
    },
    "databricks": {
        "tier": 2,
        "label": "Tier 2 — Stable",
        "features": {
            "ssl": False,
            "ssh_tunnel": False,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": False,
            "row_counts": False,
            "column_stats": False,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": False,
            "unity_catalog": True,
            "pat_auth": True,
            "table_sizes": True,
        },
    },
    "mssql": {
        "tier": 2,
        "label": "Tier 2 — Stable",
        "features": {
            "ssl": True,
            "ssh_tunnel": True,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": True,
            "row_counts": True,
            "column_stats": True,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": False,
            "table_sizes": True,
            "azure_ad_auth": True,
        },
    },
    "trino": {
        "tier": 2,
        "label": "Tier 2 — Stable",
        "features": {
            "ssl": True,
            "ssh_tunnel": False,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": False,
            "row_counts": True,
            "column_stats": False,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": True,
            "connection_pooling": False,
            "parallel_schema": False,
            "federated_query": True,
        },
    },
    "duckdb": {
        "tier": 3,
        "label": "Tier 3 — Basic",
        "features": {
            "ssl": False,
            "ssh_tunnel": False,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": False,
            "row_counts": True,
            "column_stats": False,
            "primary_keys": True,
            "comments": True,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": False,
            "connection_pooling": False,
            "parallel_schema": False,
            "motherduck": True,
        },
    },
    "sqlite": {
        "tier": 3,
        "label": "Tier 3 — Basic",
        "features": {
            "ssl": False,
            "ssh_tunnel": False,
            "schema_introspection": True,
            "foreign_keys": True,
            "indexes": False,
            "row_counts": True,
            "column_stats": False,
            "primary_keys": True,
            "comments": False,
            "sample_values": True,
            "read_only_transactions": False,
            "query_timeout": True,
            "cost_estimation": False,
            "connection_pooling": False,
            "parallel_schema": False,
        },
    },
}
