#!/usr/bin/env bash
set -euo pipefail

# SignalPilot — Cloudflare Tunnel Setup
# This script helps you configure a Cloudflare Tunnel for secure remote access.
#
# Prerequisites:
#   - A Cloudflare account (free tier works)
#   - A domain added to Cloudflare DNS
#   - cloudflared CLI installed (https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/)

BOLD='\033[1m'
CYAN='\033[36m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
RESET='\033[0m'

echo ""
echo -e "${BOLD}${CYAN}  ============================================${RESET}"
echo -e "${BOLD}${CYAN}    SignalPilot — Cloudflare Tunnel Setup${RESET}"
echo -e "${BOLD}${CYAN}  ============================================${RESET}"
echo ""

# Check for cloudflared
if ! command -v cloudflared &> /dev/null; then
  echo -e "${RED}Error: cloudflared is not installed.${RESET}"
  echo ""
  echo "Install it from: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  echo ""
  echo "Quick install:"
  echo "  macOS:   brew install cloudflared"
  echo "  Linux:   curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared"
  echo "  Docker:  docker pull cloudflare/cloudflared:latest"
  exit 1
fi

echo -e "${GREEN}cloudflared found:${RESET} $(cloudflared --version)"
echo ""

# Step 1: Login
echo -e "${BOLD}Step 1: Authenticate with Cloudflare${RESET}"
echo "This will open a browser window to authenticate."
echo ""
read -p "Press Enter to continue (or Ctrl+C to cancel)..."
cloudflared tunnel login
echo ""

# Step 2: Create tunnel
echo -e "${BOLD}Step 2: Create a tunnel${RESET}"
read -p "Enter a name for your tunnel [signalpilot]: " TUNNEL_NAME
TUNNEL_NAME="${TUNNEL_NAME:-signalpilot}"

cloudflared tunnel create "$TUNNEL_NAME"
TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
echo ""
echo -e "${GREEN}Tunnel created: ${TUNNEL_ID}${RESET}"
echo ""

# Step 3: Configure DNS
echo -e "${BOLD}Step 3: Configure DNS routing${RESET}"
read -p "Enter your domain (e.g., signalpilot.example.com): " DOMAIN
cloudflared tunnel route dns "$TUNNEL_NAME" "$DOMAIN"
echo ""
echo -e "${GREEN}DNS route created: ${DOMAIN} -> ${TUNNEL_NAME}${RESET}"
echo ""

# Step 4: Write config
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config-signalpilot.yml"

cat > "$CONFIG_FILE" <<EOF
tunnel: ${TUNNEL_ID}
credentials-file: ${CONFIG_DIR}/${TUNNEL_ID}.json

ingress:
  - hostname: ${DOMAIN}
    service: http://localhost:8080
    originRequest:
      noTLSVerify: false
      connectTimeout: 10s
  - service: http_status:404
EOF

echo -e "${GREEN}Config written to: ${CONFIG_FILE}${RESET}"
echo ""

# Step 5: Generate docker-compose override
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_OVERRIDE="${SCRIPT_DIR}/../docker-compose.tunnel.yml"

CRED_FILE="${CONFIG_DIR}/${TUNNEL_ID}.json"

cat > "$COMPOSE_OVERRIDE" <<EOF
# Auto-generated by setup-tunnel.sh
# Run: docker compose -f docker-compose.yml -f docker-compose.tunnel.yml up --build
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: sp-cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ${CONFIG_FILE}:/etc/cloudflared/config.yml:ro
      - ${CRED_FILE}:/etc/cloudflared/${TUNNEL_ID}.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mobile-gateway

  mobile-gateway:
    environment:
      TUNNEL_DOMAIN: "${DOMAIN}"
      NODE_ENV: "production"
EOF

echo -e "${GREEN}Docker Compose override written to: ${COMPOSE_OVERRIDE}${RESET}"
echo ""

# Step 6: Print summary
echo -e "${BOLD}${CYAN}  ============================================${RESET}"
echo -e "${BOLD}${CYAN}    Setup Complete!${RESET}"
echo -e "${BOLD}${CYAN}  ============================================${RESET}"
echo ""
echo "  Tunnel Name:   ${TUNNEL_NAME}"
echo "  Tunnel ID:     ${TUNNEL_ID}"
echo "  Domain:        https://${DOMAIN}"
echo "  Config:        ${CONFIG_FILE}"
echo ""
echo -e "${BOLD}To start everything:${RESET}"
echo ""
echo "  cd $(dirname "$SCRIPT_DIR")"
echo "  docker compose -f docker-compose.yml -f docker-compose.tunnel.yml up --build"
echo ""
echo -e "${BOLD}Or run the tunnel standalone:${RESET}"
echo ""
echo "  cloudflared tunnel --config ${CONFIG_FILE} run"
echo ""
echo -e "${YELLOW}Remember:${RESET}"
echo "  1. Visit https://${DOMAIN}/setup to create your admin account"
echo "  2. Enable 2FA — this is exposed to the internet!"
echo "  3. Set a strong JWT_SECRET in docker-compose.yml for persistent sessions"
echo ""
