"""Multi-notebook support for chat conversations.

A conversation can own more than one notebook. Each named notebook gets a
row in gateway_chat_conversation_notebooks; the legacy pointer columns on
the conversation keep mirroring the default "analysis" notebook.

Runtime archives gain a notebook_name column so one run can archive more
than one notebook. NULL means the legacy "analysis" notebook. The unique
identity moves from run_id alone to (run_id, notebook_name). Legacy data
has at most one archive per run, so two NULL rows per run cannot occur.

Revision ID: 0019
Revises: 0018
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "gateway_chat_conversation_notebooks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("gateway_session_id", sa.String(), nullable=False),
        sa.Column("kernel_session_id", sa.String(), nullable=False),
        sa.Column("notebook_path", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "name", name="uq_gw_conv_notebook_name"),
    )
    op.create_index(
        "ix_gw_conv_notebooks",
        "gateway_chat_conversation_notebooks",
        ["conversation_id"],
    )
    op.add_column(
        "gateway_chat_runtime_archives",
        sa.Column("notebook_name", sa.String(length=50), nullable=True),
    )
    # The old identity was unique run_id, declared unique=True on the column,
    # so postgres autogenerated this constraint name in 0006.
    op.drop_constraint(
        "gateway_chat_runtime_archives_run_id_key",
        "gateway_chat_runtime_archives",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_gw_chat_archive_run_notebook",
        "gateway_chat_runtime_archives",
        ["run_id", "notebook_name"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "uq_gw_chat_archive_run_notebook",
        "gateway_chat_runtime_archives",
        type_="unique",
    )
    op.create_unique_constraint(
        "gateway_chat_runtime_archives_run_id_key",
        "gateway_chat_runtime_archives",
        ["run_id"],
    )
    op.drop_column("gateway_chat_runtime_archives", "notebook_name")
    op.drop_index("ix_gw_conv_notebooks", table_name="gateway_chat_conversation_notebooks")
    op.drop_table("gateway_chat_conversation_notebooks")
