"""Data constants for schema linking: dialect hints, stopwords, synonyms, abbreviations, keywords, types."""

from __future__ import annotations

from typing import Any

# ── Dialect hints (Spider2.0 multi-database optimization) ─────────────────
# Tells the agent which SQL dialect to use and common pitfalls.
_DIALECT_HINTS: dict[str, dict[str, Any]] = {
    "postgres": {
        "dialect": "PostgreSQL",
        "identifier_quote": '"',
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "NOW(), CURRENT_DATE, DATE_TRUNC('month', col), EXTRACT(YEAR FROM col)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTRING()",
        "tips": ["Use :: for type casting (e.g., col::TEXT)", "ILIKE for case-insensitive LIKE"],
    },
    "mysql": {
        "dialect": "MySQL",
        "identifier_quote": "`",
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "NOW(), CURDATE(), DATE_FORMAT(col, '%Y-%m'), YEAR(col), MONTH(col)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTRING()",
        "tips": ["Use backticks for reserved words", "GROUP BY is strict — list all non-aggregated columns"],
    },
    "mssql": {
        "dialect": "T-SQL (SQL Server)",
        "identifier_quote": "[]",
        "string_quote": "'",
        "limit_syntax": "TOP n or OFFSET m ROWS FETCH NEXT n ROWS ONLY",
        "date_functions": "GETDATE(), CAST(col AS DATE), DATEPART(YEAR, col), DATEDIFF(DAY, a, b), FORMAT(col, 'yyyy-MM')",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LEN(), SUBSTRING()",
        "tips": ["Use TOP n instead of LIMIT", "Use OFFSET...FETCH for pagination", "Use [] for reserved words"],
    },
    "redshift": {
        "dialect": "Redshift (PostgreSQL-based)",
        "identifier_quote": '"',
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "GETDATE(), CURRENT_DATE, DATE_TRUNC('month', col), EXTRACT(YEAR FROM col), DATEDIFF(day, a, b)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LEN(), SUBSTRING()",
        "tips": ["PostgreSQL-like but no LATERAL joins", "Use APPROXIMATE COUNT(DISTINCT) for large tables"],
    },
    "snowflake": {
        "dialect": "Snowflake SQL",
        "identifier_quote": '"',
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "CURRENT_TIMESTAMP(), CURRENT_DATE(), DATE_TRUNC('month', col), EXTRACT(YEAR FROM col), DATEDIFF('day', a, b)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTR()",
        "tips": [
            "Identifiers are case-insensitive unless double-quoted",
            "Use FLATTEN() for semi-structured data",
            "QUALIFY for window function filtering",
        ],
    },
    "bigquery": {
        "dialect": "BigQuery Standard SQL",
        "identifier_quote": "`",
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "CURRENT_TIMESTAMP(), CURRENT_DATE(), DATE_TRUNC(col, MONTH), EXTRACT(YEAR FROM col)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTR()",
        "tips": [
            "Use backticks for project.dataset.table references",
            "Use UNNEST() for repeated fields",
            "QUALIFY for window filtering",
        ],
    },
    "clickhouse": {
        "dialect": "ClickHouse SQL",
        "identifier_quote": '"',
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "now(), today(), toStartOfMonth(col), toYear(col), dateDiff('day', a, b)",
        "string_functions": "concat(a, b), lower(), upper(), length(), substring()",
        "tips": [
            "Functions are case-sensitive and camelCase",
            "Use -If suffix for conditional aggregation (e.g., countIf, sumIf)",
            "Array functions: arrayJoin, groupArray",
        ],
    },
    "trino": {
        "dialect": "Trino SQL (ANSI-based)",
        "identifier_quote": '"',
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "CURRENT_TIMESTAMP, CURRENT_DATE, DATE_TRUNC('month', col), EXTRACT(YEAR FROM col)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTR()",
        "tips": [
            "Use catalog.schema.table for cross-catalog queries",
            "UNNEST() for arrays",
            "Supports ANSI SQL window functions",
        ],
    },
    "databricks": {
        "dialect": "Databricks SQL (Spark SQL-based)",
        "identifier_quote": "`",
        "string_quote": "'",
        "limit_syntax": "LIMIT n",
        "date_functions": "CURRENT_TIMESTAMP(), CURRENT_DATE(), DATE_TRUNC('MONTH', col), EXTRACT(YEAR FROM col)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTRING()",
        "tips": [
            "Use backticks for identifiers",
            "Supports QUALIFY for window filtering",
            "Use catalog.schema.table for Unity Catalog",
        ],
    },
    "duckdb": {
        "dialect": "DuckDB SQL (PostgreSQL-compatible)",
        "identifier_quote": '"',
        "string_quote": "'",
        "limit_syntax": "LIMIT n OFFSET m",
        "date_functions": "NOW(), CURRENT_DATE, DATE_TRUNC('month', col), EXTRACT(YEAR FROM col), DATE_DIFF('day', a, b)",
        "string_functions": "CONCAT(a, b), LOWER(), UPPER(), LENGTH(), SUBSTRING()",
        "tips": ["Very PostgreSQL-compatible", "Supports LIST and STRUCT types", "PIVOT/UNPIVOT supported natively"],
    },
}

_STOPWORDS: set[str] = {
    "the",
    "and",
    "for",
    "are",
    "but",
    "not",
    "you",
    "all",
    "can",
    "had",
    "her",
    "was",
    "one",
    "our",
    "out",
    "has",
    "how",
    "man",
    "new",
    "now",
    "old",
    "see",
    "way",
    "who",
    "did",
    "get",
    "him",
    "his",
    "let",
    "say",
    "she",
    "too",
    "use",
    "what",
    "which",
    "show",
    "find",
    "list",
    "give",
    "tell",
    "many",
    "much",
    "each",
    "every",
    "from",
    "with",
    "that",
    "this",
    "have",
    "will",
    "your",
    "they",
    "been",
    "more",
    "when",
    "make",
    "like",
    "very",
    "just",
    "than",
    "them",
    "some",
    "would",
    "could",
    "select",
    "where",
    "group",
    "having",
    "limit",
    "result",
    "table",
    "column",
    "database",
    "query",
    "display",
    "retrieve",
}

# Semantic synonyms for common business/analytical terms that map to column names
# This improves recall when the question uses different words than the schema
_SYNONYMS: dict[str, list[str]] = {
    "spending": ["amount", "total", "payment", "cost", "price", "revenue"],
    "revenue": ["amount", "total", "sales", "income", "price"],
    "bought": ["order", "purchase", "transaction"],
    "sold": ["order", "sale", "transaction"],
    "profit": ["margin", "revenue", "cost", "amount"],
    "expensive": ["price", "cost", "amount"],
    "cheapest": ["price", "cost", "amount"],
    "latest": ["date", "time", "created", "updated", "recent"],
    "oldest": ["date", "time", "created"],
    "biggest": ["count", "total", "amount", "size"],
    "active": ["status", "is_active", "enabled"],
    "inactive": ["status", "is_active", "enabled"],
    "location": ["city", "state", "country", "region", "address", "zip"],
    "address": ["city", "state", "country", "zip", "address_line"],
    "employee": ["staff", "worker", "user", "agent"],
    "customer": ["client", "buyer", "account", "user"],
    "product": ["item", "sku", "goods", "inventory"],
    "category": ["type", "group", "segment", "class"],
    "average": ["avg", "mean"],
    "monthly": ["month", "date"],
    "yearly": ["year", "date", "annual"],
    "daily": ["day", "date"],
    "payment": ["amount", "transaction", "charge", "invoice"],
    "shipping": ["shipment", "delivery", "tracking", "freight"],
    "discount": ["promo", "coupon", "rebate", "reduction"],
    "name": ["title", "label", "description"],
    "total": ["sum", "amount", "aggregate", "count"],
    "count": ["number", "total", "quantity"],
    "quantity": ["qty", "count", "amount", "units"],
    "percentage": ["percent", "rate", "ratio", "fraction"],
    "rank": ["position", "order", "rank", "rating"],
    "department": ["dept", "division", "team", "group", "unit"],
    "salary": ["wage", "pay", "compensation", "income", "earning"],
    "manager": ["supervisor", "boss", "lead", "head"],
    "country": ["nation", "region", "territory", "geo"],
    "city": ["town", "municipality", "location"],
    "email": ["mail", "contact", "address"],
    "phone": ["tel", "telephone", "mobile", "contact"],
    "created": ["created_at", "date", "timestamp", "registered"],
    "updated": ["modified", "changed", "last_modified"],
    "deleted": ["removed", "archived", "inactive"],
    "stock": ["inventory", "supply", "quantity", "available"],
    "supplier": ["vendor", "provider", "manufacturer"],
    "invoice": ["bill", "receipt", "statement", "charge"],
    "order": ["purchase", "transaction", "booking", "request"],
}

# Abbreviation expansion (common DB naming abbreviations → full words)
_ABBREVIATIONS: dict[str, list[str]] = {
    "cust": ["customer", "client"],
    "prod": ["product", "production"],
    "cat": ["category"],
    "qty": ["quantity"],
    "amt": ["amount"],
    "txn": ["transaction"],
    "inv": ["inventory", "invoice"],
    "dept": ["department"],
    "emp": ["employee"],
    "mgr": ["manager"],
    "addr": ["address"],
    "desc": ["description"],
    "num": ["number"],
    "dt": ["date"],
    "ts": ["timestamp"],
    "cnt": ["count"],
    "pct": ["percent", "percentage"],
    "avg": ["average"],
    "tot": ["total"],
    "bal": ["balance"],
    "acct": ["account"],
    "org": ["organization"],
    "loc": ["location"],
    "sku": ["product", "item"],
    "ref": ["reference"],
    "seq": ["sequence"],
    "idx": ["index"],
    "dim": ["dimension"],
    "fct": ["fact"],
    "stg": ["staging"],
}

# Question-type detection keywords
_AGG_KEYWORDS: set[str] = {
    "average",
    "avg",
    "sum",
    "total",
    "count",
    "max",
    "maximum",
    "min",
    "minimum",
    "mean",
    "median",
    "aggregate",
    "top",
    "bottom",
    "highest",
    "lowest",
    "most",
    "least",
}

_TIME_KEYWORDS: set[str] = {
    "when",
    "date",
    "year",
    "month",
    "week",
    "day",
    "quarter",
    "recent",
    "latest",
    "oldest",
    "between",
    "before",
    "after",
    "during",
    "period",
}

_NUMERIC_TYPES: set[str] = {
    "int",
    "integer",
    "bigint",
    "smallint",
    "float",
    "double",
    "decimal",
    "numeric",
    "real",
    "number",
    "money",
}

_TIME_TYPES: set[str] = {"date", "datetime", "timestamp", "timestamptz", "time"}

# String column types used for sample-value fetching (only fetch samples for string columns)
_STRING_TYPES: set[str] = {
    "character varying",
    "varchar",
    "text",
    "char",
    "character",
    "enum",
    "String",
    "VARCHAR",
    "TEXT",
    "CHAR",
    "NVARCHAR",
    "string",
}
