"use client";

import Link from "next/link";
import { Loader2, NotebookPen, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { request } from "~/lib/api";

/**
 * Agent notebooks — analyses generated by agents via the run_notebook MCP
 * tool. Each entry is an ordinary workspace-store file under the reserved
 * signalpilot-agent/ prefix, committed together with its output snapshot,
 * so opening one replays the results instantly with no kernel required
 * (the editor then attaches a kernel for further interaction).
 */

interface AgentNotebook {
  project_id: string;
  project_name: string;
  path: string;
  name: string;
  mtime: number | null;
  size: number;
  revision: number;
  has_outputs: boolean;
}

function formatWhen(mtime: number | null): string {
  if (!mtime) return "—";
  const d = new Date(mtime * 1000);
  return d.toLocaleString(undefined, {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
  });
}

export default function NotebooksPage() {
  const [notebooks, setNotebooks] = useState<AgentNotebook[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    setRefreshing(true);
    try {
      const res = await request<{ notebooks: AgentNotebook[] }>("/api/agent-notebooks");
      setNotebooks(res.notebooks);
      setError(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <div className="mx-auto max-w-4xl px-6 py-8">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">Notebooks</h1>
          <p className="mt-1 text-sm text-[var(--color-text-muted)]">
            Analyses generated by agents. Outputs replay instantly — no kernel
            needed until you start editing.
          </p>
        </div>
        <button
          type="button"
          onClick={load}
          className="flex items-center gap-1.5 rounded border border-[var(--color-border)] px-3 py-1.5 text-sm hover:bg-[var(--color-bg-hover,rgba(255,255,255,0.04))]"
          disabled={refreshing}
        >
          <RefreshCw size={14} className={refreshing ? "animate-spin" : ""} />
          Refresh
        </button>
      </div>

      {error && (
        <div className="rounded border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">
          Failed to load notebooks: {error}
        </div>
      )}

      {notebooks === null && !error && (
        <div className="flex items-center justify-center py-16 text-[var(--color-text-muted)]">
          <Loader2 size={18} className="mr-2 animate-spin" /> Loading notebooks…
        </div>
      )}

      {notebooks !== null && notebooks.length === 0 && (
        <div className="rounded border border-dashed border-[var(--color-border)] px-6 py-12 text-center text-sm text-[var(--color-text-muted)]">
          <NotebookPen size={22} className="mx-auto mb-3 opacity-60" />
          No agent notebooks yet. Ask the agent to run an analysis — notebooks
          created with the <code className="font-mono">run_notebook</code> tool
          land here automatically.
        </div>
      )}

      {notebooks !== null && notebooks.length > 0 && (
        <ul className="divide-y divide-[var(--color-border)] rounded border border-[var(--color-border)]">
          {notebooks.map((nb) => (
            <li key={`${nb.project_id}:${nb.path}`}>
              <Link
                href={`/projects?project=${encodeURIComponent(nb.project_id)}&branch=main&file=${encodeURIComponent(nb.path)}`}
                className="flex items-center gap-4 px-4 py-3 hover:bg-[var(--color-bg-hover,rgba(255,255,255,0.04))]"
              >
                <NotebookPen size={18} className="shrink-0 text-[var(--color-accent,inherit)]" />
                <div className="min-w-0 flex-1">
                  <div className="truncate font-mono text-sm">{nb.name}</div>
                  <div className="mt-0.5 text-xs text-[var(--color-text-muted)]">
                    {nb.project_name || nb.project_id.slice(0, 8)} · rev {nb.revision}
                  </div>
                </div>
                {nb.has_outputs && (
                  <span className="rounded bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-500">
                    outputs
                  </span>
                )}
                <span className="shrink-0 text-xs text-[var(--color-text-muted)]">
                  {formatWhen(nb.mtime)}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
