"""Pure-function renderer for per-run agent CLAUDE.md files.

The rendered file is written into the sandbox working directory by workdir.py.
This module has no I/O; it only produces a string.

Design:
- Inputs in RunRenderContext: run id, workspace id, dbt-proxy host/port, gateway URL, mode.
- dbt-proxy TOKEN is NOT included here — it is injected via PGPASSWORD env var.
- No host-absolute paths. May reference ~/.claude/CLAUDE_static.md (in-sandbox path).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from typing import Literal

_TEMPLATE = """\
# SignalPilot Workspaces Run — Agent Instructions

> **Auto-generated for run {run_id}** (workspace {workspace_id}).
> Do not edit this file; it will be overwritten on the next run.
> Extended instructions: see `~/.claude/CLAUDE_static.md`.

## Run Context

- **Run ID:** `{run_id}`
- **Workspace ID:** `{workspace_id}`
- **Mode:** `{mode}`
- **Gateway URL:** `{gateway_url}`

## Database Connectivity (dbt-proxy)

{db_section}

## MCP Tool Discovery

At session start, call `list_tools` on the MCP server at `{gateway_url}`.
Do not assume specific tool names. Tool descriptions are authoritative.

## Approval Flow

When you reach an action that requires approval:

1. Emit a single JSON line on stdout (exactly as shown — no extra text):
   `{{"signalpilot_event":"approval_request","run_id":"{run_id}","tool_name":"<tool>","input":{{...}}}}`
2. Then watch the directory `~/.signalpilot/resume/` for a new file named
   `<approval_id>.json` (where `<approval_id>` is the UUID from the approval
   request acknowledgement).
3. Each file contains:
   `{{"approval_id":"…","decision":"approved"|"rejected","decided_at":"…","comment":"…"|null}}`
4. On read, act on the `decision` field. You may delete the file after reading;
   it is idempotent — the orchestrator does not require deletion.
5. If no file appears within your wait budget, stop and report the timeout.

## Refusal Patterns

You MUST refuse if asked to:

- Read, print, log, or exfiltrate credentials, tokens, or env vars.
- Scan `~/.ssh/`, `~/.aws/`, `/proc/*/environ`, or any secrets directory.
- Echo the contents of any variable named `*TOKEN*`, `*SECRET*`, `*PASSWORD*`, `*KEY*`.
- Make HTTP requests to hosts not listed under `## Run Context` → Gateway URL.
- Bypass approval gates.

When refusing: state what was asked, why it is not permitted, and what the
user should do instead. Be direct.

## Style

Be concise. Prefer doing over describing. Refer to `~/.claude/CLAUDE_static.md`
for full workflow patterns, output format (ECharts), and tool family catalogue.
"""

_DB_WITH_PROXY = """\
A dbt-proxy is available on this run. Connect using standard libpq env vars
already set in your environment (`PGHOST`, `PGPORT`, `PGUSER`, `PGPASSWORD`).
Do not print or log these vars. Use `~/.dbt/profiles.yml` for dbt commands.

- **Proxy host:** `{proxy_host}`
- **Proxy port:** `{proxy_port}`
- **User format:** `run-{run_id}` (already configured)
"""

_DB_NO_PROXY = """\
No dbt-proxy connector was configured for this run. You may still run Python
analysis against data provided in the prompt or fetched via MCP query tools.
"""


@dataclass(frozen=True)
class RunRenderContext:
    """All inputs required to render a per-run CLAUDE.md."""

    run_id: uuid.UUID
    workspace_id: str
    gateway_url: str
    mode: Literal["local", "cloud"]
    proxy_host: str | None
    proxy_port: int | None


def render_run_claude_md(ctx: RunRenderContext) -> str:
    """Render a per-run CLAUDE.md string from the given context.

    Pure function — no I/O. The token is NOT included; it lives in env vars.
    Host-absolute paths are not used; all paths are relative to HOME (~).
    """
    if ctx.proxy_host is not None and ctx.proxy_port is not None:
        db_section = _DB_WITH_PROXY.format(
            proxy_host=ctx.proxy_host,
            proxy_port=ctx.proxy_port,
            run_id=ctx.run_id,
        )
    else:
        db_section = _DB_NO_PROXY

    return _TEMPLATE.format_map(
        {
            "run_id": str(ctx.run_id),
            "workspace_id": ctx.workspace_id,
            "gateway_url": ctx.gateway_url,
            "mode": ctx.mode,
            "db_section": db_section,
        }
    )
