server_tokens off;
access_log off;

server {
    listen 9000;

    location / {
        limit_except GET HEAD { deny all; }
        proxy_pass http://minio:9000;
        proxy_set_header Host $http_host;
        proxy_request_buffering off;
        proxy_buffering off;
    }
}
