"""Generate docs/docs/product/roles.mdx from the gateway permission vocabulary.

Run from the repository root:

    python docs/scripts/gen-roles.py

The gateway test ``tests/test_roles_doc.py`` renders the same page and fails
when the committed file differs, so the page cannot drift from
``gateway/auth/permissions.py``.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GATEWAY_DIR = REPO_ROOT / "signalpilot" / "gateway"
DOC_PATH = REPO_ROOT / "docs" / "docs" / "product" / "roles.mdx"

_HEADER = """---
sidebar_position: 12
sidebar_label: Roles
---

{/* Generated by docs/scripts/gen-roles.py from gateway/auth/permissions.py. Do not edit by hand. */}

# Roles: what admins and members can do

Every SignalPilot organization has two roles, the ones Clerk gives you: **admin**
and **member**. The rule is short:

- **Org resources: admins write, members read.** Connections, settings, integrations,
  keys and secrets, the published knowledge base, projects and repository links,
  eval configuration, budgets, billing.
- **User resources: the owner writes.** Conversations, notebooks, personal MCP
  connectors, personal secrets, your own dashboards and reports, your own API keys.
  Admins can also change these when moderation is needed.
- **Read is broad, write is narrow.** Members see every org resource they need to do
  work; they cannot change org configuration or spend org money on their own authority.

"Admin" here is the role inside your organization, not SignalPilot staff. An API key
inherits the role of the person who minted it: a key with the `admin` scope acts as an
admin, and members cannot mint one.

## Permissions

The server sends this permission set to the web app (`GET /api/me` and the chat
bootstrap), which hides or disables controls a member cannot use, so a member never
opens an editor that fails on save. A disabled control carries the tooltip
*Only org admins can change this*.

"""

_FOOTER = """
## What members see

- **Read-only, not hidden**: connections (credentials redacted) with a *Managed by your
  org admins* note where the edit form would be; schema, lineage and dbt maps; the
  knowledge base with a *Propose an entry* action; eval results; project files with
  settings shown as values.
- **Hidden from the sidebar**: BYOK, org settings and chat defaults, security status,
  billing, usage, audit, team management. A direct link shows *Org admins manage this*.
- **Fully editable**: conversations, notebooks, personal MCP connectors, personal secrets,
  their dashboards and reports, their personal API keys.

## Production branches

Writes through the workspace files API to a project's default branch (its production
branch) require an admin. Members work on other branches.
"""


def _load_permissions():
    sys.path.insert(0, str(GATEWAY_DIR))
    from gateway.auth.permissions import (  # noqa: PLC0415
        _ADMIN_PERMISSION_DESCRIPTIONS,
        _MEMBER_PERMISSION_DESCRIPTIONS,
    )

    return _ADMIN_PERMISSION_DESCRIPTIONS, _MEMBER_PERMISSION_DESCRIPTIONS


def render() -> str:
    admin_rows, member_rows = _load_permissions()
    out = [_HEADER]
    out.append("### Member and admin\n\n")
    out.append("| Permission | What it allows |\n|---|---|\n")
    for name, description in member_rows:
        out.append(f"| `{name}` | {description} |\n")
    out.append("\n### Admin only\n\n")
    out.append("| Permission | What it allows |\n|---|---|\n")
    for name, description in admin_rows:
        out.append(f"| `{name}` | {description} |\n")
    out.append(_FOOTER)
    return "".join(out)


def main() -> int:
    DOC_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
