"""SQLAlchemy models for gateway-owned tables.

These tables live in the same PostgreSQL database as the backend tables but are
managed by the gateway's own Alembic migrations (version_table=gateway_alembic_version).

This package splits the models by domain. Each submodule registers its tables
on the one shared GatewayBase.metadata. Import order matches the original
single-module definition order.
"""

from __future__ import annotations

from .base import (
    SSL_SECRET_FIELDS,
    GatewayBase,
    TZDateTime,
    strip_ssl_secrets,
)
from .chat import (
    GatewayChatArtifact,
    GatewayChatConversation,
    GatewayChatFile,
    GatewayChatMessage,
    GatewayChatRun,
    GatewayChatRunEvent,
    GatewayChatShareGrant,
    GatewayChatStarterCache,
    GatewayChatUserPreference,
    GatewayReportRefresh,
    GatewayReportShareAccess,
    GatewayReportShareGrant,
    GatewaySavedReport,
    GatewaySavedReportVersion,
)
from .core import (
    GatewayAuditLog,
    GatewayBYOKKey,
    GatewayConnection,
    GatewayCredential,
    GatewayHealthEvent,
    GatewayOrg,
    GatewayProject,
    GatewaySessionBudget,
    GatewaySetting,
    GatewayUploadSession,
)
from .evals import (
    GatewayEvalAccuracyHistory,
    GatewayEvalConfig,
    GatewayEvalRegression,
    GatewayEvalRun,
    GatewayEvalRunTask,
    GatewayImprovementRun,
)
from .integrations import (
    GatewayNotionIntegration,
    GatewaySlackThreadWatch,
    NotionDeliverable,
    NotionDeliverableContextSnapshot,
    NotionDeliverableUpdate,
    NotionInstallation,
    NotionInstallationConfig,
    NotionOAuthState,
    NotionWebhookDelivery,
    SlackInstallation,
    SlackInstallationConfig,
    SlackOAuthState,
)
from .knowledge import (
    GatewayApiKey,
    GatewayKnowledgeDoc,
    GatewayKnowledgeEdit,
    GatewayKnowledgeRetrieval,
    GatewayReport,
    GatewaySchemaWatch,
)
from .queries import (
    GatewayAnalysisTrail,
    GatewayChatObjectDeletion,
    GatewayChatRuntimeArchive,
    GatewayChatTraceEvent,
    GatewayChatTraceThread,
    GatewayDashboard,
    GatewayDashboardAuthoringSession,
    GatewayDashboardResult,
    GatewayDashboardVersion,
    GatewayGovernedQueryExecution,
    GatewayQueryApproval,
    GatewayQueryPlan,
    GatewayQueryProposal,
    GatewayRuntimeDataset,
    GatewayStructuredQueryResult,
)
from .runtime import (
    GatewayAgentRun,
    GatewayDbtManifest,
    GatewayGitHubInstallation,
    GatewayGitHubRepoLink,
    GatewayNotebookSession,
    GatewayOrgSecrets,
    GatewayUserSecrets,
)
from .workspace import (
    GatewayProjectBranch,
    GatewayUserSession,
    GatewayWorkspaceLease,
    GatewayWorkspaceProject,
    GatewayWorkspaceRevision,
)

__all__ = [
    "GatewayAgentRun",
    "GatewayAnalysisTrail",
    "GatewayApiKey",
    "GatewayAuditLog",
    "GatewayBYOKKey",
    "GatewayBase",
    "GatewayChatArtifact",
    "GatewayChatConversation",
    "GatewayChatFile",
    "GatewayChatMessage",
    "GatewayChatObjectDeletion",
    "GatewayChatRun",
    "GatewayChatRunEvent",
    "GatewayChatRuntimeArchive",
    "GatewayChatShareGrant",
    "GatewayChatStarterCache",
    "GatewayChatTraceEvent",
    "GatewayChatTraceThread",
    "GatewayChatUserPreference",
    "GatewayConnection",
    "GatewayCredential",
    "GatewayDashboard",
    "GatewayDashboardAuthoringSession",
    "GatewayDashboardResult",
    "GatewayDashboardVersion",
    "GatewayDbtManifest",
    "GatewayEvalAccuracyHistory",
    "GatewayEvalConfig",
    "GatewayEvalRegression",
    "GatewayEvalRun",
    "GatewayEvalRunTask",
    "GatewayGitHubInstallation",
    "GatewayGitHubRepoLink",
    "GatewayGovernedQueryExecution",
    "GatewayHealthEvent",
    "GatewayImprovementRun",
    "GatewayKnowledgeDoc",
    "GatewayKnowledgeEdit",
    "GatewayKnowledgeRetrieval",
    "GatewayNotebookSession",
    "GatewayNotionIntegration",
    "GatewayOrg",
    "GatewayOrgSecrets",
    "GatewayProject",
    "GatewayProjectBranch",
    "GatewayQueryApproval",
    "GatewayQueryPlan",
    "GatewayQueryProposal",
    "GatewayReport",
    "GatewayReportRefresh",
    "GatewayReportShareAccess",
    "GatewayReportShareGrant",
    "GatewayRuntimeDataset",
    "GatewaySavedReport",
    "GatewaySavedReportVersion",
    "GatewaySchemaWatch",
    "GatewaySessionBudget",
    "GatewaySetting",
    "GatewaySlackThreadWatch",
    "GatewayStructuredQueryResult",
    "GatewayUploadSession",
    "GatewayUserSecrets",
    "GatewayUserSession",
    "GatewayWorkspaceLease",
    "GatewayWorkspaceProject",
    "GatewayWorkspaceRevision",
    "NotionDeliverable",
    "NotionDeliverableContextSnapshot",
    "NotionDeliverableUpdate",
    "NotionInstallation",
    "NotionInstallationConfig",
    "NotionOAuthState",
    "NotionWebhookDelivery",
    "SSL_SECRET_FIELDS",
    "SlackInstallation",
    "SlackInstallationConfig",
    "SlackOAuthState",
    "TZDateTime",
    "strip_ssl_secrets",
]
