/**
 * Client-side parser for the SignalPilot notebook `.py` file format.
 *
 * This is a TypeScript port of the parsing behavior implemented in
 * notebook-server (signalpilot/_ast/parse.py + load.py) so the browser can
 * render a notebook from its file contents without a Python kernel.
 *
 * Contract:
 *  - `parseNotebookPy(code)` returns `{ notebook }` (a NotebookV1) when the
 *    contents are a well-formed SignalPilot notebook, or `null` when they are
 *    not — the caller should then fall back to a raw source view.
 *  - Cell `code` matches exactly what the Python side records as cell code
 *    (verified against fixtures generated by the real Python serializer in
 *    `__fixtures__/`).
 *  - `code_hash` is md5 of the utf-8 code (null for empty code), matching
 *    signalpilot/_session/state/serialize.py::_hash_code.
 *  - Cell `id` is a fresh random CellId (ids are not stored in the file);
 *    the setup cell always gets the well-known id/name "setup".
 *  - Top-level `@app.function` / `@app.class_definition` cells are named
 *    `*<name>` (TOPLEVEL_CELL_PREFIX) and their code is the def/class source
 *    verbatim, exactly as the Python cell manager records them.
 */

import type { SyntaxNode } from "@lezer/common";
import { parser } from "@lezer/python";

import type { Notebook } from "@/packages/sp-api";
import { CellId, SETUP_CELL_ID } from "@/core/cells/ids";
import { hashCellCode } from "./md5";

type NotebookV1 = Notebook["NotebookV1"];
type NotebookCell = Notebook["NotebookCell"];
type NotebookCellConfig = Notebook["NotebookCellConfig"];

const SETUP_CELL_NAME = "setup";
const DEFAULT_CELL_NAME = "_";
const TOPLEVEL_CELL_PREFIX = "*";

// ---------------------------------------------------------------------------
// Text helpers (mirroring textwrap.dedent semantics used by the Python parser)
// ---------------------------------------------------------------------------

/** Longest common leading-whitespace prefix of all non-blank lines, removed. */
function dedent(text: string): string {
  const lines = text.split("\n");
  let prefix: string | null = null;
  for (const line of lines) {
    if (line.trim() === "") {
      continue;
    }
    const indent = line.slice(0, line.length - line.trimStart().length);
    if (prefix === null) {
      prefix = indent;
    } else {
      let i = 0;
      while (i < prefix.length && i < indent.length && prefix[i] === indent[i]) {
        i++;
      }
      prefix = prefix.slice(0, i);
    }
    if (prefix === "") {
      return text;
    }
  }
  if (prefix === null || prefix === "") {
    return text;
  }
  const p = prefix;
  return lines
    .map((line) => (line.trim() === "" ? line : line.slice(p.length)))
    .join("\n");
}

function dropTrailingBlankLines(lines: string[]): string[] {
  let end = lines.length;
  while (end > 0 && lines[end - 1].trim() === "") {
    end--;
  }
  return lines.slice(0, end);
}

// ---------------------------------------------------------------------------
// Lezer helpers
// ---------------------------------------------------------------------------

interface Src {
  text: string;
  lines: string[];
  lineStarts: number[];
}

function makeSrc(text: string): Src {
  const lines = text.split("\n");
  const lineStarts: number[] = new Array(lines.length);
  let pos = 0;
  for (let i = 0; i < lines.length; i++) {
    lineStarts[i] = pos;
    pos += lines[i].length + 1;
  }
  return { text, lines, lineStarts };
}

/** 0-indexed line containing `pos`. */
function lineOf(src: Src, pos: number): number {
  let lo = 0;
  let hi = src.lineStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (src.lineStarts[mid] <= pos) {
      lo = mid;
    } else {
      hi = mid - 1;
    }
  }
  return lo;
}

function nodeText(src: Src, node: SyntaxNode): string {
  return src.text.slice(node.from, node.to);
}

function children(node: SyntaxNode): SyntaxNode[] {
  const out: SyntaxNode[] = [];
  for (let c = node.firstChild; c; c = c.nextSibling) {
    out.push(c);
  }
  return out;
}

function hasSyntaxError(node: SyntaxNode): boolean {
  const cursor = node.cursor();
  do {
    if (cursor.type.isError) {
      return true;
    }
  } while (cursor.next());
  return false;
}

type Kwargs = Record<string, string | number | boolean | null>;

/**
 * Extract constant keyword arguments from an ArgList node
 * (`(a=1, b=True, c="x")`). Returns null when the arg list contains
 * anything that is not a simple `name=<constant>` pair.
 */
function parseKwargs(src: Src, argList: SyntaxNode | null): Kwargs | null {
  const kwargs: Kwargs = {};
  if (!argList) {
    return kwargs;
  }
  const items = children(argList).filter(
    (c) => c.name !== "(" && c.name !== ")" && c.name !== ",",
  );
  for (let i = 0; i < items.length; i += 3) {
    const nameNode = items[i];
    const opNode = items[i + 1];
    const valueNode = items[i + 2];
    if (
      !nameNode ||
      !opNode ||
      !valueNode ||
      nameNode.name !== "VariableName" ||
      opNode.name !== "AssignOp"
    ) {
      return null;
    }
    const value = constantValue(src, valueNode);
    if (value === undefined) {
      return null;
    }
    kwargs[nodeText(src, nameNode)] = value;
  }
  return kwargs;
}

function constantValue(
  src: Src,
  node: SyntaxNode,
): string | number | boolean | null | undefined {
  const text = nodeText(src, node);
  switch (node.name) {
    case "Boolean":
      return text === "True";
    case "None":
      return null;
    case "Number": {
      const value = Number(text);
      return Number.isFinite(value) ? value : undefined;
    }
    case "String":
      return parsePyStringLiteral(text);
    case "UnaryExpression": {
      // Negative numbers: -1
      const kids = children(node);
      if (
        kids.length === 2 &&
        kids[0].name === "ArithOp" &&
        nodeText(src, kids[0]) === "-" &&
        kids[1].name === "Number"
      ) {
        const value = Number(nodeText(src, kids[1]));
        return Number.isFinite(value) ? -value : undefined;
      }
      return undefined;
    }
    default:
      return undefined;
  }
}

/**
 * Decode a Python string literal's source text. Handles the forms the
 * codegen emits: optional r/b/u/f prefixes, single or triple quotes. In
 * non-raw strings only backslash escapes of the "take next char literally"
 * kind are decoded (codegen only ever emits `\\` and `\"`).
 */
function parsePyStringLiteral(literal: string): string | undefined {
  const match = /^([A-Za-z]{0,2})("""|'''|"|')([\S\s]*)\2$/.exec(literal);
  if (!match) {
    return undefined;
  }
  const prefix = match[1].toLowerCase();
  if (prefix.includes("f")) {
    return undefined;
  }
  const content = match[3];
  if (prefix.includes("r")) {
    return content;
  }
  return content.replaceAll(/\\([\S\s])/g, "$1");
}

// ---------------------------------------------------------------------------
// Cell extraction
// ---------------------------------------------------------------------------

function makeConfig(kwargs: Kwargs): NotebookCellConfig {
  return {
    column: typeof kwargs.column === "number" ? kwargs.column : null,
    disabled: kwargs.disabled === true,
    hide_code: kwargs.hide_code === true,
  };
}

function makeCell(
  code: string,
  name: string,
  config: NotebookCellConfig,
  id?: string,
): NotebookCell {
  return {
    code,
    code_hash: hashCellCode(code),
    config,
    id: id ?? CellId.create(),
    name,
  };
}

/** Statements of a Body node (skipping the leading ":" token). */
function bodyStatements(body: SyntaxNode): SyntaxNode[] {
  return children(body).filter((c) => c.name !== ":");
}

/**
 * Extract the code of an `@app.cell` function: the dedented body, without
 * the signature and without the trailing `return ...` statement (plus any
 * blank lines immediately before it).
 */
function extractCellBody(src: Src, fnNode: SyntaxNode): string | null {
  const body = fnNode.getChild("Body");
  if (!body) {
    return null;
  }
  const stmts = bodyStatements(body);
  if (stmts.length === 0) {
    return null;
  }
  const defLine = lineOf(src, fnNode.from);
  const firstLine = lineOf(src, stmts[0].from);
  const last = stmts[stmts.length - 1];

  if (firstLine === lineOf(src, body.from)) {
    // Body on the same line as the signature. The codegen never emits this
    // except conceptually for empty cells; accept `def _(): return` only.
    if (stmts.length === 1 && last.name === "ReturnStatement") {
      return "";
    }
    return null;
  }
  if (defLine === firstLine) {
    return null;
  }

  let endLine: number;
  if (last.name === "ReturnStatement") {
    endLine = lineOf(src, last.from) - 1;
  } else {
    endLine = lineOf(src, last.to - 1);
  }
  if (endLine < firstLine) {
    return "";
  }
  const lines = dropTrailingBlankLines(src.lines.slice(firstLine, endLine + 1));
  if (lines.length === 0) {
    return "";
  }
  return dedent(lines.join("\n"));
}

/** Extract the dedented body of a `with app.setup:` block. */
function extractSetupBody(src: Src, withNode: SyntaxNode): string | null {
  const body = withNode.getChild("Body");
  if (!body) {
    return null;
  }
  const stmts = bodyStatements(body);
  if (stmts.length === 0) {
    return null;
  }
  const firstLine = lineOf(src, stmts[0].from);
  if (firstLine === lineOf(src, withNode.from)) {
    return null;
  }
  const last = stmts[stmts.length - 1];
  const endLine = lineOf(src, last.to - 1);
  const lines = dropTrailingBlankLines(src.lines.slice(firstLine, endLine + 1));
  let code = dedent(lines.join("\n"));
  // The Python serializer appends a `pass` when the setup block contains
  // only comments; its parser removes it symmetrically.
  if (code.endsWith("\npass")) {
    code = code.slice(0, -"\npass".length);
  }
  return code;
}

/**
 * Decorator info: which app attribute (`cell`, `function`,
 * `class_definition`) and its constant kwargs.
 */
interface DecoratorInfo {
  attr: string;
  kwargs: Kwargs;
}

function parseAppDecorator(src: Src, dec: SyntaxNode): DecoratorInfo | null {
  const kids = children(dec).filter((c) => c.name !== "At" && c.name !== ".");
  // Shape: VariableName("app") VariableName(attr) [ArgList]
  if (
    kids.length < 2 ||
    kids[0].name !== "VariableName" ||
    nodeText(src, kids[0]) !== "app" ||
    kids[1].name !== "VariableName"
  ) {
    return null;
  }
  const attr = nodeText(src, kids[1]);
  const argList = kids[2] && kids[2].name === "ArgList" ? kids[2] : null;
  if (kids.length > 3 || (kids.length === 3 && !argList)) {
    return null;
  }
  const kwargs = parseKwargs(src, argList);
  if (kwargs === null) {
    return null;
  }
  return { attr, kwargs };
}

/** True when `node` is `app.<attr>` or `app.<attr>(...)`. */
function isAppMember(src: Src, node: SyntaxNode, attr: string): boolean {
  let member = node;
  if (node.name === "CallExpression") {
    const first = node.firstChild;
    if (!first) {
      return false;
    }
    member = first;
  }
  if (member.name !== "MemberExpression") {
    return false;
  }
  const kids = children(member).filter((c) => c.name !== ".");
  return (
    kids.length === 2 &&
    kids[0].name === "VariableName" &&
    nodeText(src, kids[0]) === "app" &&
    kids[1].name === "PropertyName" &&
    nodeText(src, kids[1]) === attr
  );
}

/** Match `app.<attr>` / `app.<attr>(kwargs...)`; returns kwargs or null. */
function matchAppCall(
  src: Src,
  node: SyntaxNode,
  attr: string,
): Kwargs | null {
  if (!isAppMember(src, node, attr)) {
    return null;
  }
  const argList =
    node.name === "CallExpression" ? node.getChild("ArgList") : null;
  return parseKwargs(src, argList);
}

function parseUnparsableCell(
  src: Src,
  callNode: SyntaxNode,
): NotebookCell | null {
  const argList = callNode.getChild("ArgList");
  if (!argList) {
    return null;
  }
  const items = children(argList).filter(
    (c) => c.name !== "(" && c.name !== ")" && c.name !== ",",
  );
  if (items.length === 0 || items[0].name !== "String") {
    return null;
  }
  const raw = parsePyStringLiteral(nodeText(src, items[0]));
  if (raw === undefined) {
    return null;
  }
  // Remaining items are kwargs (name=..., hide_code=..., ...)
  const kwargItems = items.slice(1);
  const kwargs: Kwargs = {};
  for (let i = 0; i < kwargItems.length; i += 3) {
    const nameNode = kwargItems[i];
    const opNode = kwargItems[i + 1];
    const valueNode = kwargItems[i + 2];
    if (
      !nameNode ||
      !opNode ||
      !valueNode ||
      nameNode.name !== "VariableName" ||
      opNode.name !== "AssignOp"
    ) {
      return null;
    }
    const value = constantValue(src, valueNode);
    if (value === undefined) {
      return null;
    }
    kwargs[nodeText(src, nameNode)] = value;
  }
  const code = dedent(raw).trim();
  const name =
    typeof kwargs.name === "string" && kwargs.name !== ""
      ? kwargs.name
      : DEFAULT_CELL_NAME;
  return makeCell(code, name, makeConfig(kwargs));
}

// ---------------------------------------------------------------------------
// Notebook parsing
// ---------------------------------------------------------------------------

const RUN_GUARD_RE =
  /^if\s+__name__\s*==\s*("__main__"|'__main__')\s*:\s*\r?\n?\s*app\.run\(\)\s*$/;

export function parseNotebookPy(code: string): { notebook: NotebookV1 } | null {
  const text = code.trim();
  if (!text) {
    return null;
  }
  const tree = parser.parse(text);
  if (hasSyntaxError(tree.topNode)) {
    return null;
  }
  const src = makeSrc(text);

  const top = children(tree.topNode);
  let index = 0;
  const next = () => (index < top.length ? top[index] : null);

  // -- header: comments (not in the tree at top level? they are) + docstrings
  let node = next();
  let sawImport = false;
  while (node) {
    if (node.name === "Comment") {
      index++;
      node = next();
      continue;
    }
    if (node.name === "ExpressionStatement") {
      // Module docstring in the header
      const kids = children(node);
      if (kids.length === 1 && kids[0].name === "String") {
        index++;
        node = next();
        continue;
      }
      return null;
    }
    break;
  }

  // -- import signalpilot [as <alias>]
  let alias = "sp";
  if (node && node.name === "ImportStatement") {
    const match = /^import\s+signalpilot(?:\s+as\s+([A-Za-z_]\w*))?$/.exec(
      nodeText(src, node).trim(),
    );
    if (!match) {
      return null;
    }
    alias = match[1] ?? "signalpilot";
    sawImport = true;
    index++;
    node = next();
  }
  if (!sawImport) {
    return null;
  }

  // -- __generated_with = "<version>" (optional)
  let version: string | null = null;
  if (node && node.name === "AssignStatement") {
    const kids = children(node);
    if (
      kids.length === 3 &&
      kids[0].name === "VariableName" &&
      nodeText(src, kids[0]) === "__generated_with" &&
      kids[1].name === "AssignOp" &&
      kids[2].name === "String"
    ) {
      version = parsePyStringLiteral(nodeText(src, kids[2])) ?? null;
      index++;
      node = next();
    }
  }

  // -- app = <alias>.App(...)
  {
    if (!node || node.name !== "AssignStatement") {
      return null;
    }
    const kids = children(node);
    if (
      kids.length !== 3 ||
      kids[0].name !== "VariableName" ||
      nodeText(src, kids[0]) !== "app" ||
      kids[1].name !== "AssignOp" ||
      kids[2].name !== "CallExpression"
    ) {
      return null;
    }
    const call = kids[2];
    const fn = call.firstChild;
    if (!fn || fn.name !== "MemberExpression") {
      return null;
    }
    const fnKids = children(fn).filter((c) => c.name !== ".");
    if (
      fnKids.length !== 2 ||
      fnKids[0].name !== "VariableName" ||
      nodeText(src, fnKids[0]) !== alias ||
      fnKids[1].name !== "PropertyName" ||
      nodeText(src, fnKids[1]) !== "App"
    ) {
      return null;
    }
    // App kwargs (layout config etc.) are not part of NotebookV1; validated
    // only for structure.
    index++;
    node = next();
  }

  const cells: NotebookCell[] = [];

  // -- optional setup block
  while (node && node.name === "Comment") {
    index++;
    node = next();
  }
  if (node && node.name === "WithStatement") {
    const kids = children(node).filter(
      (c) => c.name !== "with" && c.name !== "async" && c.name !== "Body",
    );
    if (kids.length !== 1) {
      return null;
    }
    const kwargs = matchAppCall(src, kids[0], "setup");
    if (kwargs === null) {
      return null;
    }
    const setupCode = extractSetupBody(src, node);
    if (setupCode === null) {
      return null;
    }
    cells.push(
      makeCell(setupCode, SETUP_CELL_NAME, makeConfig(kwargs), SETUP_CELL_ID),
    );
    index++;
    node = next();
  }

  // -- body cells until the run guard
  let sawRunGuard = false;
  while (node) {
    if (node.name === "Comment") {
      index++;
      node = next();
      continue;
    }
    if (node.name === "IfStatement") {
      if (!RUN_GUARD_RE.test(nodeText(src, node).trim())) {
        return null;
      }
      sawRunGuard = true;
      break;
    }
    if (node.name === "DecoratedStatement") {
      const decorators = children(node).filter((c) => c.name === "Decorator");
      const target =
        node.getChild("FunctionDefinition") ?? node.getChild("ClassDefinition");
      if (decorators.length !== 1 || !target) {
        return null;
      }
      const info = parseAppDecorator(src, decorators[0]);
      if (!info) {
        return null;
      }
      if (info.attr === "cell") {
        if (target.name !== "FunctionDefinition") {
          return null;
        }
        const nameNode = target.getChild("VariableName");
        const cellCode = extractCellBody(src, target);
        if (!nameNode || cellCode === null) {
          return null;
        }
        cells.push(
          makeCell(cellCode, nodeText(src, nameNode), makeConfig(info.kwargs)),
        );
      } else if (
        (info.attr === "function" && target.name === "FunctionDefinition") ||
        (info.attr === "class_definition" && target.name === "ClassDefinition")
      ) {
        const nameNode = target.getChild("VariableName");
        if (!nameNode) {
          return null;
        }
        const startLine = lineOf(src, target.from);
        const endLine = lineOf(src, target.to - 1);
        const lines = dropTrailingBlankLines(
          src.lines.slice(startLine, endLine + 1),
        );
        const cellCode = lines.join("\n").trimEnd();
        cells.push(
          makeCell(
            cellCode,
            TOPLEVEL_CELL_PREFIX + nodeText(src, nameNode),
            makeConfig(info.kwargs),
          ),
        );
      } else {
        return null;
      }
      index++;
      node = next();
      continue;
    }
    if (node.name === "ExpressionStatement") {
      const call = node.firstChild;
      if (
        call &&
        call.name === "CallExpression" &&
        isAppMember(src, call, "_unparsable_cell")
      ) {
        const cell = parseUnparsableCell(src, call);
        if (!cell) {
          return null;
        }
        cells.push(cell);
        index++;
        node = next();
        continue;
      }
      return null;
    }
    return null;
  }

  // Everything after the run guard is ignored (mirrors the Python parser,
  // which stops at the guard). A missing guard is a soft violation there,
  // so we tolerate it too.
  void sawRunGuard;

  const notebook: NotebookV1 = {
    cells,
    metadata: { sp_version: version },
    version: "1",
  };
  return { notebook };
}
