import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'quickstart',
    'concepts',
    'system-overview',
    'workspaces',
    {
      type: 'category',
      label: 'Setup',
      collapsed: false,
      items: [
        'setup/install',
        'setup/cloud',
        'setup/onboarding',
        'setup/self-hosting-production',
        'setup/configuration',
        'setup/operations',
        'workflows/claude-md-recipes',
      ],
    },
    {
      type: 'category',
      label: 'Connect Your Stack',
      collapsed: false,
      items: [
        'connect-database',
        'product/connections-ui',
        'connect-notion',
        'integrations',
        'setup/ssh-tunneling',
        'mcp/connect-claude-code',
        'mcp/connect-other-clients',
        'mcp/multiple-mcps',
        'mcp/auth',
      ],
    },
    {
      type: 'category',
      label: 'Using SignalPilot',
      collapsed: false,
      items: [
        'product/knowledge-base',
        'product/projects',
        'product/query-console',
        'product/schema-explorer',
        'product/audit',
        'product/activity',
        'product/demo-warehouse',
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      collapsed: true,
      items: [
        'settings/overview',
        'settings/github',
        'settings/byok',
      ],
    },
    {
      type: 'category',
      label: 'Databases',
      collapsed: true,
      items: [
        'databases/overview',
        'databases/postgresql',
        'databases/mysql',
        'databases/snowflake',
        'databases/bigquery',
        'databases/redshift',
        'databases/clickhouse',
        'databases/databricks',
        'databases/mssql',
        'databases/trino',
        'databases/duckdb',
        'databases/sqlite',
      ],
    },
    {
      type: 'category',
      label: 'Plugin',
      collapsed: false,
      items: [
        'plugin',
        'plugin/install',
        'plugin/codex',
        'plugin/skills-overview',
        'plugin/skills-reference',
        'plugin/verifier-agent',
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        'how-it-works',
        'workflows/dbt-build',
        'workflows/verification',
        'workflows/sql-exploration',
        'workflows/custom-workflow',
      ],
    },
    {
      type: 'category',
      label: 'Evals',
      collapsed: false,
      items: [
        'evals/overview',
        'evals/quickstart',
        'evals/eval-repo',
        'evals/write-tasks',
        'evals/running',
        'evals/deploying',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/tools-overview',
        'reference/tools-query',
        'reference/tools-schema',
        'reference/tools-dbt',
        'reference/tools-ops',
        'reference/governance',
        'reference/rest-api',
        'reference/dialects',
        'architecture',
        'security',
      ],
    },
  ],
};

export default sidebars;
