import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Cloud-first information architecture. Reading order for a new user runs
// top to bottom: start, connect an AI tool, use the product, bring in data,
// extend, then the engineering sections. Self-hosting and reference material
// are collapsed at the bottom on purpose.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      className: 'sp-cat sp-cat-start',
      items: ['home', 'quickstart', 'concepts', 'cloud'],
    },
    {
      type: 'category',
      label: 'Connect your AI tool',
      collapsed: false,
      className: 'sp-cat sp-cat-connect',
      items: [
        'clients/claude',
        'clients/chatgpt',
        'clients/claude-code',
        'clients/other-tools',
        'clients/api-keys',
        'clients/multiple-mcps',
      ],
    },
    {
      type: 'category',
      label: 'Use SignalPilot',
      collapsed: false,
      className: 'sp-cat sp-cat-product',
      items: [
        'product/chat',
        'product/knowledge-base',
        'product/dashboards',
        'product/chat-files',
        'product/projects',
        'product/query-console',
        'product/schema-explorer',
        'product/audit',
        'product/activity',
        'workspaces',
      ],
    },
    {
      type: 'category',
      label: 'Bring in your data',
      collapsed: false,
      className: 'sp-cat sp-cat-data',
      items: [
        'connect-database',
        'product/connections-ui',
        'product/demo-warehouse',
        'connect-notion',
        'integrations',
        {
          type: 'category',
          label: 'Database guides',
          collapsed: true,
          items: [
            'databases/overview',
            'databases/postgresql',
            'databases/mysql',
            'databases/snowflake',
            'databases/bigquery',
            'databases/redshift',
            'databases/clickhouse',
            'databases/databricks',
            'databases/mssql',
            'databases/trino',
            'databases/duckdb',
            'databases/sqlite',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Extend and administer',
      collapsed: false,
      className: 'sp-cat sp-cat-extend',
      items: [
        'settings/connectors',
        'settings/overview',
        'settings/github',
        'settings/byok',
        'security',
      ],
    },
    {
      type: 'category',
      label: 'Agent workflows',
      collapsed: true,
      className: 'sp-cat sp-cat-agents',
      items: [
        'how-it-works',
        'plugin',
        'plugin/install',
        'plugin/codex',
        'plugin/skills-overview',
        'plugin/skills-reference',
        'plugin/verifier-agent',
        'workflows/dbt-build',
        'workflows/verification',
        'workflows/sql-exploration',
        'workflows/custom-workflow',
        'workflows/claude-md-recipes',
      ],
    },
    {
      type: 'category',
      label: 'Evals',
      collapsed: true,
      className: 'sp-cat sp-cat-evals',
      items: [
        'evals/overview',
        'evals/quickstart',
        'evals/eval-repo',
        'evals/write-tasks',
        'evals/running',
        'evals/deploying',
      ],
    },
    {
      type: 'category',
      label: 'Self-host',
      collapsed: true,
      className: 'sp-cat sp-cat-selfhost',
      items: [
        'self-host/install',
        'self-host/configuration',
        'self-host/production',
        'self-host/operations',
        'self-host/ssh-tunneling',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      className: 'sp-cat sp-cat-reference',
      items: [
        'reference/tools-overview',
        'reference/tools-query',
        'reference/tools-schema',
        'reference/tools-dbt',
        'reference/tools-ops',
        'reference/governance',
        'reference/rest-api',
        'reference/dialects',
        'architecture',
        'system-overview',
      ],
    },
  ],
};

export default sidebars;
